/**
 * Vendors the three brand typefaces into public/fonts/.
 *
 * Renders must not depend on fonts.gstatic.com at frame time: a network hiccup
 * mid-render silently substitutes a fallback face, and the failure shows up as
 * a subtly wrong video rather than an error. Self-hosting also keeps the
 * render reproducible on a machine with no outbound access.
 *
 * Only the latin subsets and the weights the video actually uses are fetched,
 * which is also why the render no longer makes ~370 font requests per frame.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../public/fonts");

// A desktop UA is required, or Google serves the legacy .ttf CSS.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

/** family → the axis/weight spec, matching what the scenes use. */
const FAMILIES = [
  { name: "Fraunces", spec: "opsz,wght@9..144,500;9..144,600", css: "Fraunces" },
  { name: "Inter", spec: "wght@400;500;600", css: "Inter" },
  { name: "IBM+Plex+Mono", spec: "wght@500", css: "IBM Plex Mono" },
];

/** Subsets to keep. The video is English-only; the rest is dead weight. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

await mkdir(OUT, { recursive: true });

const blocks = [];

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.name}:${family.spec}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Failed to fetch CSS for ${family.name}: ${res.status}`);
  const css = await res.text();

  // Each @font-face is preceded by a /* subset */ comment; keep only latin ones.
  const chunks = css.split("/*").slice(1);
  for (const chunk of chunks) {
    const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
    if (!KEEP_SUBSETS.has(subset)) continue;

    const face = chunk.slice(chunk.indexOf("*/") + 2);
    const srcMatch = face.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    const weightMatch = face.match(/font-weight:\s*([^;]+);/);
    if (!srcMatch) continue;

    const remote = srcMatch[1];
    const fileName = `${family.css.replace(/\s+/g, "")}-${(weightMatch?.[1] ?? "x")
      .trim()
      .replace(/\s+/g, "_")}-${subset}.woff2`;

    const bin = await fetch(remote, { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`Failed to download ${remote}: ${bin.status}`);
    await writeFile(join(OUT, fileName), Buffer.from(await bin.arrayBuffer()));

    // Relative to fonts.css, which sits in the same directory.
    blocks.push(face.replace(remote, fileName).trim());
    console.log(`  ✓ ${fileName}`);
  }
}

await writeFile(
  join(OUT, "fonts.css"),
  "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n" +
    blocks.join("\n\n") +
    "\n",
  "utf8",
);

console.log(`\nWrote ${blocks.length} @font-face rules to public/fonts/fonts.css`);
