import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 320, height: 844 } });
const page = await ctx.newPage();
await page.goto("http://localhost:4173/");
await page.waitForTimeout(600);
const brand = await page.getByText("Roamly Flow", { exact: true }).first().boundingBox();
const control = await page.getByRole("button", { name: "Replay the app tour" }).boundingBox();
console.log("brand right edge:", brand ? (brand.x + brand.width).toFixed(1) : null, "| controls left edge:", control?.x.toFixed(1), "| gap:", control && brand ? (control.x - brand.x - brand.width).toFixed(1) : null);
await browser.close();
